# Generated by Django 3.2.6 on 2022-03-31 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('totalDesc', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('totalOpGravada', models.DecimalField(decimal_places=2, max_digits=6)),
                ('totalIGV', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precioEnvio', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pagado', models.BooleanField(default=False)),
                ('users', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('size', models.CharField(choices=[('1', '0-3 meses'), ('2', '3-6 meses'), ('3', '6-12 meses'), ('4', '12-18 meses'), ('5', '18-24 meses'), ('6', '2 años'), ('7', '3 años')], default='0-6 meses', max_length=50)),
                ('stock', models.IntegerField(default=1)),
                ('prodGender', models.CharField(choices=[('1', 'Niño'), ('2', 'Niña'), ('3', 'Unisex')], default='1', max_length=1)),
                ('cantVendidos', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prodCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ecommerce.category')),
            ],
        ),
        migrations.CreateModel(
            name='BoletaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioUni', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('opGravada', models.DecimalField(decimal_places=2, max_digits=6)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('estado', models.BooleanField(default=False)),
                ('boleta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='ecommerce.boleta')),
                ('productos', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='boletaDetalle', to='ecommerce.product')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
