# Generated by Django 3.2.6 on 2022-03-31 23:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='DosageForm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodCat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodGender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='dci',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='dosageForm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='ecommerce.dosageform'),
        ),
        migrations.AddField(
            model_name='product',
            name='dose',
            field=models.CharField(default='100 mg', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='tradename',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
