# Generated by Django 3.2.6 on 2022-04-03 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_dosageform_cantprod'),
        ('ecommerce', '0002_auto_20220331_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dosageForm',
        ),
        migrations.AlterField(
            model_name='boletadetalle',
            name='productos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='boletaDetalle', to='pharmacy.product'),
        ),
        migrations.DeleteModel(
            name='DosageForm',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
