# Generated by Django 3.1.7 on 2022-04-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_dosageform_product'),
        ('pharmacy', '0003_auto_20220401_1804'),
    ]

    operations = [
    ]
