# Generated by Django 3.2.6 on 2022-04-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_dosageform_cantprod'),
        ('pharmacy', '0005_merge_20220404_2101'),
    ]

    operations = [
    ]
