# Generated by Django 3.2.6 on 2022-04-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_auto_20220408_1124'),
        ('pharmacy', '0007_auto_20220408_1203'),
    ]

    operations = [
    ]
